name: 'Check and update shared-modules'
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  shared-modules-auto-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: flathub/actions/shared-modules-auto-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.FLATHUBBOT_TOKEN }}
